# Generated by Django 3.1.4 on 2023-10-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=100)),
                ('nan', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Etxea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('herria', models.CharField(max_length=100)),
                ('pertsonaKop', models.IntegerField()),
                ('pertsona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alokairuak.pertsona')),
            ],
        ),
    ]
